spring.application.name=app

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Smartvet
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.show-sql=true

# LA REGLA DE ORO: Dile a Hibernate que NO modifique nuestra base de datos.
# Solo debe leerla y escribir datos, no alterar las tablas.
spring.jpa.hibernate.ddl-auto=none
